image: node:10.15.3

pipelines:
    branches:
      master:
          - step:
              name: Build and Upload to S3
              script:
                - apt-get update
                - apt-get install -y zip
                - zip -r application.zip .
                - pipe: atlassian/aws-code-deploy:0.2.10
                  variables:
                    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                    COMMAND: 'upload'
                    APPLICATION_NAME: ${APPLICATION_NAME}
                    ZIP_FILE: 'application.zip'
                    S3_BUCKET: ${S3_BUCKET}

          - step:
              name: Deploy with CodeDeploy
              deployment: test
              script:
                - pipe: atlassian/aws-code-deploy:0.2.10
                  variables:
                    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                    S3_BUCKET: ${S3_BUCKET}
                    COMMAND: 'deploy'
                    APPLICATION_NAME: ${APPLICATION_NAME}
                    DEPLOYMENT_GROUP: ${DEPLOYMENT_GROUP}
                    IGNORE_APPLICATION_STOP_FAILURES: 'true'
                    FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
                    WAIT: 'true'
